name: Playwright Coverage

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  playwright-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.testing .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Publish Ziggy Configuration
        run: php artisan ziggy:generate

      - name: Start Vite
        run: LARAVEL_BYPASS_ENV_CHECK=1 npm run dev -- --host &

      - name: Add starter-kit.test to /etc/hosts
        run: echo "127.0.0.1 starter-kit.test" | sudo tee -a /etc/hosts

      - name: Run migrations
        run: php artisan migrate --force

      - name: Seed database
        run: php artisan db:seed --force

      - name: Start Laravel server
        run: php artisan serve --host=starter-kit.test --port=8000 &

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: LARAVEL_BYPASS_ENV_CHECK=1 npx playwright test